{% set version = "1.0" %}

package:
  name: prosstt
  version: {{ version }}

source:
  fn: prosstt-{{ version }}.tar.gz
  url: https://github.com/soedinglab/prosstt/archive/v{{ version }}.tar.gz
  sha256: 24437d4e3ba869b8f2c7f6ceee0d791d7abffbf640542cfac432516a2e5af3ff

build:
  number: 0
  script: pip install .
  skip: True  # [not py36]

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas
    - matplotlib
    - jupyter
    - scanpy

test:
  imports:
    - prosstt
    - prosstt.tree
    - prosstt.simulation
    - prosstt.count_model
    - prosstt.tree_utils
    - prosstt.sim_utils

about:
  home: https://github.com/soedinglab/prosstt/
  license: GPL3
  license_file: LICENSE
  summary: "PROSSTT: PRObabilistic Simulations of ScRNA-seq Tree-like Topologies"